# Site settings
title: Viktoras Makauskas blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  An experimental blog setup for now.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://viktorasm.github.io" # the base hostname & protocol for your site
twitter_username: viktorasm
github_username:  viktorasm

# Build settings
markdown: kramdown
